### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by ravi2krishna** [ravi2krishna/login-2412#1]
1. Create an index.html page
2. Update Two Text Fields i.e Username & Password
3. Update a button with Login
4. Add Person Image Avatar in page 
5. A checkbox with Remember Me
6. A Cancel Button
7. Link with Forgot Password
![image](https://github.com/ravi2krishna/login-2412/assets/5461468/023b2d26-5314-4add-bb39-c00e5cdd6dd7)

**Comment by vamshi4251** [comment]
done with image and text alignment
